### ISSUE TITLE
surfdrive geeft een foutmelding, waarschijnlijk update nodig

### ISSUE THREAD

**Issue by JakoVerstraate** [autopkg/bochoven-recipes#17]
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Mismatch in authority names
CodeSignatureVerifier: Expected: Developer ID Installer: ownCloud Inc. (9B5WD74GWJ) -> Developer ID Certification Authority -> Apple Root CA
CodeSignatureVerifier: Found:    Developer ID Installer: ownCloud GmbH (4AP2STM4H5) -> Developer ID Certification Authority -> Apple Root CA
Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Failed.
Receipt written to /Users/adm/Library/AutoPkg/Cache/local.munki.surfdrive/receipts/surfdrive.munki-receipt-20190704-073742.plist
The following recipes failed:
    surfdrive.munki.recipe
        Error in local.munki.surfdrive: Processor: CodeSignatureVerifier: Error: Mismatch in authority names. Note that all verification can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.
Nothing downloaded, packaged or imported.

**Comment by bochoven** [comment]
Fixed with f93aac02bd3e4a25f0a3ef8e18b00a522cd6bc84
