### ISSUE TITLE
Opera recipe is not currently working

### ISSUE THREAD

**Issue by thenikola** [autopkg/bochoven-recipes#4]
It appears that your Opera recipe now downloads a tar.gz file which autopkg does not yet support.

I've opened a ticket with AutoPkg. https://github.com/autopkg/autopkg/issues/162

**Comment by gregneagle** [comment]
The Unarchiver processor definitely handles .tar.gz files:

https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/Unarchiver.py#L29
https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/Unarchiver.py#L125-L135
