### ISSUE TITLE
JASP Download recipe warning

### ISSUE THREAD

**Issue by eshirk** [autopkg/bochoven-recipes#46]
Seeing the following warning during code signature verification:

CodeSignatureVerifier: WARNING: This recipe is using 'requirements' when it should be using 'requirement'. This will become an error in future versions of AutoPkg.

**Comment by homebysix** [comment]
The fix is included in https://github.com/autopkg/bochoven-recipes/pull/42.

**Comment by eshirk** [comment]
Ah right--thanks, and will close this issue.
