### ISSUE TITLE
JASP download changes, current recipe failing

### ISSUE THREAD

**Issue by hfike** [autopkg/bochoven-recipes#51]
JASP now has both Intel and AS builds available. The download at the existing URL in the download recipe downloads the Intel build (JASP-0.16.2.0-macOS-x86_64.dmg) and the following URL downloads the AS build (JASP-0.16.2.0-macOS-arm64.dmg) https://jasp-stats.org/thank-you-for-downloading-jasp-macos-apple-silicon/

Because of the architecture being appended to the name of the dmg that is downloaded, the current recipe is failing:
The following recipes failed:
    JASP.munki
        Error in local.munki.JASP: Processor: URLTextSearcher: Error: No match found on URL: https://jasp-stats.org/thank-you-for-downloading-jasp-macos/

**Comment by bochoven** [comment]
Thanks for reporting! I’m not deploying Jasp anymore, so if anyone wants to step in and take over the recipe, please let me know. If you gave a fix, PR is always welcome!

**Comment by eshirk** [comment]
Here's my attempted fix: 
https://github.com/autopkg/bochoven-recipes/pull/52

**Comment by bochoven** [comment]
lgtm
