### ISSUE TITLE
PsychPy2 needs an updated download recipe

### ISSUE THREAD

**Issue by jg-at-gu** [autopkg/bochoven-recipes#7]
The download recipe only recognizes versions up to and including 1.85.6 because they have changed the naming convention.

Old string is: ^StandalonePsychoPy-.*-OSX_64bit.dmg$

New string (should be?): ^StandalonePsychoPy-.*-MacOS$

**Comment by bochoven** [comment]
Fixed with 81aa4880e6e874c1d06c8752f16653cb9bc5ad47
