### ISSUE TITLE
ADF Usage?

### ISSUE THREAD

**Issue by jonbrown21** [autopkg/bochoven-recipes#8]
I am not sure I am using your munki recipe correctly so please LMK if this is a bug or if this is just something I need to sort out on my end. 

When I run the ADF.munki.recipe I get this

```
Curl failure: The requested URL returned error: 401 Unauthorized (exit code 22)
Failed.
```

Am I supposed to override the downloads recipe and add in credentials or is the recipe broken?

**Comment by bochoven** [comment]
You need credentials, please contact SCM about access.

**Comment by jonbrown21** [comment]
Thanks.
